"""
Data preprocessing for F-TDM with Trusted Worker Mechanism.

Reads AirQuality_MCS.csv (generated by generate_dataset.py) and builds
support/query task splits for MAML training.

Training data types : CO(GT), PT08.S1(CO), C6H6(GT), PT08.S2(NMHC), NO2(GT), T
Test data type      : NOx(GT)

Each row in AirQuality_MCS.csv is already one PoI:
  D_W = [value_1, value_2, value_3, value_4]   (worker observations)
  D_U = true_value                               (UAV / ground truth)

Normalization: MinMaxScaler fitted on true_value per data type, then applied
to all worker values for that type.

Returns worker_ids alongside data for evaluation (not used as model input).
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

MCS_CSV = "AirQuality_MCS.csv"

TRAIN_TYPES = [
    "CO(GT)",
    "PT08.S1(CO)",
    "C6H6(GT)",
    "PT08.S2(NMHC)",
    "NO2(GT)",
    "T",
]
TEST_TYPE = "NOx(GT)"

# MAML task split parameters
SUPPORT_SIZE = 10  # maximum support size (k); tasks sampled up to this


def _load_mcs(path: str = MCS_CSV) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["timestamp"])
    return df


def _fit_scaler(df: pd.DataFrame, dtype: str) -> MinMaxScaler:
    scaler = MinMaxScaler()
    true_vals = df.loc[df["data_type"] == dtype, "true_value"].values.reshape(-1, 1)
    scaler.fit(true_vals)
    return scaler


def _normalize_group(df_type: pd.DataFrame, scaler: MinMaxScaler) -> pd.DataFrame:
    """Return a copy with all value columns normalised."""
    df_type = df_type.copy()
    for col in ["true_value", "value_1", "value_2", "value_3", "value_4"]:
        df_type[col] = scaler.transform(df_type[col].values.reshape(-1, 1)).ravel()
    return df_type


def _df_to_arrays(df: pd.DataFrame):
    """Extract X (worker values), y (true values), worker_id arrays."""
    X = df[["value_1", "value_2", "value_3", "value_4"]].values.astype(np.float32)
    y = df["true_value"].values.astype(np.float32).reshape(-1, 1)
    wids = df[
        ["worker_id_1", "worker_id_2", "worker_id_3", "worker_id_4"]
    ].values.astype(np.int64)
    return X, y, wids


def build_tasks(
    df_type: pd.DataFrame,
    support_size: int,
    n_tasks: int,
    rng: np.random.Generator,
):
    """
    Build (support_X, support_y, query_X, query_y) task tuples.

    Parameters
    ----------
    df_type     : normalised DataFrame for one data type
    support_size: k — number of support PoIs per task
    n_tasks     : number of tasks to sample
    rng         : numpy random generator

    Returns
    -------
    list of (sup_X, sup_y, qry_X, qry_y) as float32 numpy arrays
    """
    X, y, _ = _df_to_arrays(df_type)
    n = len(X)
    tasks = []
    for _ in range(n_tasks):
        idx = rng.permutation(n)
        sup_idx = idx[:support_size]
        qry_idx = idx[support_size : support_size * 2]
        if len(qry_idx) == 0:
            continue
        tasks.append(
            (
                X[sup_idx],
                y[sup_idx],
                X[qry_idx],
                y[qry_idx],
            )
        )
    return tasks


def load_and_preprocess(
    mcs_path: str = MCS_CSV,
    support_size: int = SUPPORT_SIZE,
    n_tasks: int = 500,
    seed: int = 42,
):
    """
    Load MCS dataset and return everything needed for training and testing.

    Returns
    -------
    train_tasks_by_type : dict mapping data_type -> list of (sup_X, sup_y, qry_X, qry_y)
    test_data     : dict with keys 'X', 'y', 'worker_ids' for NOx test set
    scalers       : dict mapping data_type -> MinMaxScaler
    nox_scaler    : MinMaxScaler fitted on NOx true_value (for inverse transform)
    """
    rng = np.random.default_rng(seed)
    df = _load_mcs(mcs_path)

    scalers = {}
    train_tasks_by_type = {}

    # ── Training types ────────────────────────────────────────────────────────
    for dtype in TRAIN_TYPES:
        scaler = _fit_scaler(df, dtype)
        scalers[dtype] = scaler
        df_type = _normalize_group(df[df["data_type"] == dtype].reset_index(drop=True), scaler)
        tasks = build_tasks(df_type, support_size=support_size, n_tasks=n_tasks, rng=rng)
        train_tasks_by_type[dtype] = tasks

    # ── Test type (NOx) ───────────────────────────────────────────────────────
    nox_scaler = _fit_scaler(df, TEST_TYPE)
    scalers[TEST_TYPE] = nox_scaler
    df_nox = _normalize_group(
        df[df["data_type"] == TEST_TYPE].reset_index(drop=True), nox_scaler
    )
    test_X, test_y, test_wids = _df_to_arrays(df_nox)

    test_data = {
        "X": test_X,
        "y": test_y,
        "worker_ids": test_wids,
    }

    return train_tasks_by_type, test_data, scalers, nox_scaler
